AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template used for building the infrastructure to implement a lambda function AMP Website  Validator.

Resources:
  HTMLValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: test-amp-website.testAMPWebsite
      Runtime: nodejs14.x
      Timeout: 60
      Layers:
        - !Ref DependenciesLayers
      MemorySize: 512

      Events: 
        ExplicitApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpValidatorApi
            Path: /test
            Method: get

#  DependenciesLayers:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#      LayerName: Dependencies-layer
#      Description: Python dependencies needed to run the lambda function code
#      ContentUri: package/
#      CompatibleRuntimes:
#        - python3.8

  DependenciesLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-dependencies
      Description: Dependencies for sam app 
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x



  HttpValidatorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Tags:
        Tag: Value
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      StageVariables:
        StageVar: Value
      FailOnWarnings: true


Outputs:
  LambdaApi:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpValidatorApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/test'
  HttpApiId:
    Description: Api id of HttpValidatorApi
    Value:
      Ref: HttpValidatorApi
  LambdaFunction:
    Description: "HTML Validator Lambda Function"
    Value: !GetAtt HTMLValidatorFunction.Arn